import os

def format_width(width):
    w = width.strip()
    if not w or w == "1":
        return ""
    if not w.startswith("["):
        return f" [{w}]"
    return f" {w}"

def format_task_width(width):
    w = width.strip()
    if not w or w == "1":
        return ""
    if not w.startswith("["):
        return f" [{w}]"
    return f"{w} "

def generate_module_code(module_name, ports):
    """
    Generates SystemVerilog code for the module skeleton.
    """
    if not module_name:
        module_name = "unnamed_module"
        
    code = []
    code.append("// ==========================================================================")
    code.append(f"// Module: {module_name}")
    code.append("// Generated by SystemVerilog Tool")
    code.append("// ==========================================================================")
    code.append(f"module {module_name} (")
    
    port_lines = []
    for i, port in enumerate(ports):
        name = port["name"] or f"port_{i}"
        direction = "input " if port["dir"] == "IN" else "output"
        if port["dir"] == "INOUT":
            direction = "inout "
            
        width_str = format_width(port["width"])
        dir_pad = direction.ljust(7)
        type_str = "logic"
        w_pad = width_str.ljust(8) if width_str else "        "
        
        line = f"    {dir_pad} {type_str} {w_pad} {name}"
        port_lines.append(line)
        
    code.append(",\n".join(port_lines))
    code.append(");")
    code.append("")
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Module Implementation")
    code.append("    // ----------------------------------------------------------------------")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)

def generate_testbench_code(module_name, ports, is_sync_reset=False, is_active_low_reset=True, tb_mode="standalone"):
    """
    Generates an advanced SystemVerilog testbench.
    tb_mode can be "standalone" or "chained" (With Master).
    """
    if not module_name:
        module_name = "unnamed_module"
        
    tb_name = f"{module_name}_tb"
    
    # Identify clock and reset
    clk_port = None
    rst_port = None
    
    for p in ports:
        name_lower = p["name"].lower()
        if p["dir"] == "IN":
            if name_lower in ["clk", "clock", "i_clk"]:
                clk_port = p
            elif name_lower in ["rst", "reset", "rst_n", "i_rst", "rst_b"]:
                rst_port = p
                
    # Fallback search
    if not clk_port:
        for p in ports:
            if p["dir"] == "IN" and "clk" in p["name"].lower():
                clk_port = p
                break
    if not rst_port:
        for p in ports:
            if p["dir"] == "IN" and "rst" in p["name"].lower():
                rst_port = p
                break

    code = []
    
    # 1. Color Macros
    code.append("`define CLR_RESET  \"\\033[0m\"")
    code.append("`define CLR_RED    \"\\033[1;31m\"")
    code.append("`define CLR_GREEN  \"\\033[1;32m\"")
    code.append("`define CLR_YELLOW \"\\033[1;33m\"")
    code.append("`define CLR_BLUE   \"\\033[1;34m\"")
    code.append("")
    
    if clk_port:
        code.append("`define PERIOD 10")
        code.append("")
        
    code.append("`timescale 1ns / 1ps")
    code.append(f"string formatted_msg_{module_name};")
    code.append("")
    code.append(f"module {tb_name};")
    code.append("")
    
    # 2. Stats
    code.append("    int errors = 0;")
    code.append("    int tests_run = 0;")
    code.append("")
    
    # 3. Signal Declarations
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Signals")
    code.append("    // ----------------------------------------------------------------------")
    
    max_name_len = max([len(p["name"]) for p in ports]) if ports else 10
    clk_name = clk_port["name"] if clk_port else None
    
    for port in ports:
        name = port["name"]
        width_str = format_width(port["width"])
        w_pad = width_str + " " if width_str else ""
        
        if name == clk_name:
            code.append(f"    logic {name} = 0;")
        else:
            code.append(f"    logic {w_pad}{name};")
            
    code.append("")
    
    # 4. Clock Generation (if clk exists)
    if clk_name:
        code.append("    always")
        code.append("        #(`PERIOD/2) " + clk_name + " = ~" + clk_name + ";")
        code.append("")

    # 5. DUT Instantiation
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // DUT Instantiation")
    code.append("    // ----------------------------------------------------------------------")
    code.append(f"    {module_name} dut (")
    
    inst_lines = []
    for port in ports:
        name = port["name"]
        inst_lines.append(f"        .{name:<{max_name_len}} ({name})")
    code.append(",\n".join(inst_lines))
    code.append("    );")
    code.append("")
    
    # 6. Verification Task
    task_inputs = [p for p in ports if p["dir"] == "IN" and p["name"] != clk_name]
    task_outputs = [p for p in ports if p["dir"] == "OUT" or p["dir"] == "INOUT"]
    
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Verification Task")
    code.append("    // ----------------------------------------------------------------------")
    code.append(f"    task verification_{module_name}(")
    
    task_args = []
    for p in task_inputs:
        w = format_task_width(p["width"])
        task_args.append(f"        input  logic {w}{p['name']}_test")
        
    for p in task_outputs:
        w = format_task_width(p["width"])
        task_args.append(f"        input  logic {w}{p['name']}_expect")
        
    code.append(",\n".join(task_args))
    code.append("    );")
    code.append("        begin")
    code.append("            tests_run++;")
    code.append("")
    code.append("            // Apply inputs")
    for p in task_inputs:
        code.append(f"            {p['name']} = {p['name']}_test;")
    
    if clk_name:
        code.append("            #(`PERIOD);")
    else:
        code.append("            #10;")
        
    code.append("")
    
    # Check condition
    checks = []
    for p in task_outputs:
        checks.append(f"{p['name']} !== {p['name']}_expect")
    check_cond = " || ".join(checks) if checks else "1'b0"
    
    # Format error/success logs
    err_format_args = ["tests_run"]
    err_format_str = f"  [ ERROR ] Test %02d: "
    in_prints = []
    for p in task_inputs:
        in_prints.append(f"{p['name']}:%h")
        err_format_args.append(f"{p['name']}_test")
    err_format_str += " ".join(in_prints)
    
    out_prints = []
    for p in task_outputs:
        out_prints.append(f"Actual {p['name']}:%h (Expected:%h)")
        err_format_args.append(p["name"])
        err_format_args.append(f"{p['name']}_expect")
    err_format_str += " | " + ", ".join(out_prints)
    
    success_format_args = ["tests_run"]
    success_format_str = f"  [SUCCESS] Test %02d: "
    success_in_prints = []
    for p in task_inputs:
        success_in_prints.append(f"{p['name']}:%h")
        success_format_args.append(f"{p['name']}_test")
    success_format_str += " ".join(success_in_prints)
    
    success_out_prints = []
    for p in task_outputs:
        success_out_prints.append(f"{p['name']}:%h")
        success_format_args.append(p["name"])
    success_format_str += " = " + ", ".join(success_out_prints)

    code.append(f"            if ({check_cond}) begin")
    code.append(f"                formatted_msg_{module_name} = $sformatf(\"{err_format_str}\",")
    code.append("                    " + ", ".join(err_format_args) + ");")
    code.append(f"                $display(\"%s%s%s\", `CLR_RED, formatted_msg_{module_name}, `CLR_RESET);")
    code.append("                errors++;")
    code.append("            end else begin")
    code.append(f"                formatted_msg_{module_name} = $sformatf(\"{success_format_str}\",")
    code.append("                    " + ", ".join(success_format_args) + ");")
    code.append(f"                $display(\"%s%s%s\", `CLR_GREEN, formatted_msg_{module_name}, `CLR_RESET);")
    code.append("            end")
    code.append("        end")
    code.append("    endtask")
    code.append("")
    
    # 7. Initial block
    code.append("    initial begin")
    
    # Master Start wait trigger
    if tb_mode == "chained":
        code.append("        // Wait for master start trigger")
        code.append("        @(master_tb.master_is_done);")
        code.append("")
        
    # Stand-alone waveform dumping
    if tb_mode == "standalone":
        code.append("        // Waveform dumping")
        code.append("        $dumpfile(\"build/simulation.vcd\");")
        code.append(f"        $dumpvars(0, {tb_name});")
        code.append("")
        
    # Title display
    code.append(f"        formatted_msg_{module_name} = $sformatf(\"-- {module_name} Test Bench --\");")
    code.append(f"        $display(\"%s%s%s\", `CLR_BLUE, formatted_msg_{module_name}, `CLR_RESET);")
    
    # Apply initial reset if exists
    if rst_port:
        rst_name = rst_port["name"]
        init_val = "0" if is_active_low_reset else "1"
        deassert_val = "1" if is_active_low_reset else "0"
        code.append(f"        {rst_name} = {init_val};")
        code.append("        #20;")
        code.append(f"        {rst_name} = {deassert_val};")
        code.append("")
        
    # Default Warning
    code.append("        // Warning by default")
    code.append("        $display(\"%s[ WARNING ] Test cases not implemented!%s\", `CLR_RED, `CLR_RESET);")
    code.append("")
    
    # Test case templates
    code.append("        // ==========================================")
    code.append("        // 1. Initial Test Cases")
    code.append("        // ==========================================")
    code.append("        $display(\"* Running test cases...\");")
    
    # Generate mock arguments
    mock_args_test = []
    mock_args_expect = []
    
    for p in task_inputs:
        val = "0"
        if p["name"] == rst_port["name"] if rst_port else False:
            val = "1" if is_active_low_reset else "0"
        elif p["width"] != "1":
            val = "8'h00"
        mock_args_test.append(val)
        
    for p in task_outputs:
        val = "0"
        if p["width"] != "1":
            val = "8'h00"
        mock_args_expect.append(val)
        
    all_mock_args = mock_args_test + mock_args_expect
    args_str = ", ".join(all_mock_args)
    
    code.append(f"        verification_{module_name}({args_str});")
    code.append("")
    
    # Print End results
    code.append("        // ==========================================")
    code.append("        // End of Simulation")
    code.append("        // ==========================================")
    code.append(f"        formatted_msg_{module_name} = $sformatf(\"   END : %0d Tests executed | %0d Errors(s)\", tests_run, errors);")
    code.append(f"        if (errors == 0) $display(\"%s%s%s\", `CLR_GREEN, formatted_msg_{module_name}, `CLR_RESET);")
    code.append(f"        else             $display(\"%s%s%s\", `CLR_RED, formatted_msg_{module_name}, `CLR_RESET);")
    code.append("")
    
    # Event Trigger at end (if chained)
    if tb_mode == "chained":
        code.append(f"        // Trigger completion event in master")
        code.append(f"        -> master_tb.{module_name}_is_done;")
        code.append("")
        
    if tb_mode == "standalone":
        code.append("        $finish;")
        
    code.append("    end")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)

def generate_master_tb_code(sub_tbs):
    """
    Generates a top-level master_tb module matching the user's updated event format.
    """
    code = []
    code.append("`timescale 1ns / 1ps")
    code.append("")
    code.append("module master_tb;")
    code.append("")
    code.append("    // Synchronization Events")
    code.append("    event master_is_done;")
    
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"    event {name}_is_done;")
    code.append("")
    
    code.append("    // Sub-Testbench Instantiations")
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"    {name}_tb u_{name}_tb();")
    code.append("")
    
    code.append("    initial begin")
    code.append("        $dumpfile(\"build/simulation.vcd\");")
    code.append("        $dumpvars(0, master_tb); // Record all signals recursively")
    code.append("        ")
    code.append("        // Start all testbenches")
    code.append("        -> master_is_done;")
    code.append("        ")
    code.append("        // Wait for each testbench to complete sequentially")
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"        @({name}_is_done);")
    code.append("        ")
    code.append("        $finish;")
    code.append("    end")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)
