import os

def format_width(width):
    w = width.strip()
    if not w or w == "1":
        return ""
    # Ensure it starts with space and contains brackets
    if not w.startswith("["):
        return f" [{w}]"
    return f" {w}"

def generate_module_code(module_name, ports):
    """
    Generates SystemVerilog code for the module skeleton.
    """
    if not module_name:
        module_name = "unnamed_module"
        
    code = []
    code.append("// ==========================================================================")
    code.append(f"// Module: {module_name}")
    code.append("// Generated by SystemVerilog Tool")
    code.append("// ==========================================================================")
    code.append(f"module {module_name} (")
    
    # Format ports
    port_lines = []
    
    # Let's align fields: direction, type, width, name
    for i, port in enumerate(ports):
        name = port["name"] or f"port_{i}"
        direction = "input " if port["dir"] == "IN" else "output"
        if port["dir"] == "INOUT":
            direction = "inout "
            
        width_str = format_width(port["width"])
        
        # We align: direction (7 chars) + type (5 chars: logic) + width (variable) + name
        # E.g. "input  logic [7:0]  data_in"
        dir_pad = direction.ljust(7)
        type_str = "logic"
        
        # If width_str is empty, we don't need double spaces
        w_pad = width_str.ljust(8) if width_str else "        "
        
        line = f"    {dir_pad} {type_str} {w_pad} {name}"
        port_lines.append(line)
        
    # Join with commas
    code.append(",\n".join(port_lines))
    code.append(");")
    code.append("")
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Module Implementation")
    code.append("    // ----------------------------------------------------------------------")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)

def generate_testbench_code(module_name, ports, is_sync_reset=False, is_active_low_reset=True):
    """
    Generates a SystemVerilog testbench skeleton for the module.
    """
    if not module_name:
        module_name = "unnamed_module"
        
    tb_name = f"tb_{module_name}"
    
    # Identify clock and reset
    clk_port = None
    rst_port = None
    
    for p in ports:
        name_lower = p["name"].lower()
        if p["dir"] == "IN":
            if name_lower in ["clk", "clock", "i_clk"]:
                clk_port = p
            elif name_lower in ["rst", "reset", "rst_n", "i_rst", "rst_b"]:
                rst_port = p
                
    # Fallback search
    if not clk_port:
        for p in ports:
            if p["dir"] == "IN" and "clk" in p["name"].lower():
                clk_port = p
                break
    if not rst_port:
        for p in ports:
            if p["dir"] == "IN" and "rst" in p["name"].lower():
                rst_port = p
                break

    code = []
    code.append("`timescale 1ns / 1ps")
    code.append("// ==========================================================================")
    code.append(f"// Testbench: {tb_name}")
    code.append(f"// Target:    {module_name}")
    code.append("// Generated by SystemVerilog Tool")
    code.append("// ==========================================================================")
    code.append(f"module {tb_name};")
    code.append("")
    
    # A. Signal Declarations
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Testbench Signals")
    code.append("    // ----------------------------------------------------------------------")
    
    max_name_len = max([len(p["name"]) for p in ports]) if ports else 10
    
    # We declare inputs as logic (to drive them) and outputs as logic/wire
    for port in ports:
        name = port["name"]
        width_str = format_width(port["width"])
        w_pad = width_str + " " if width_str else ""
        
        # Inputs are driven in initial block -> logic
        # Outputs can be logic or wire -> logic is standard in SV
        sig_type = "logic"
        
        # Align signal declarations
        align_pad = " " * (max_name_len - len(name))
        code.append(f"    {sig_type:<5} {w_pad}{name};")
        
    code.append("")
    
    # B. DUT Instantiation
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Device Under Test (DUT) Instantiation")
    code.append("    // ----------------------------------------------------------------------")
    code.append(f"    {module_name} dut (")
    
    inst_lines = []
    for port in ports:
        name = port["name"]
        align_pad = " " * (max_name_len - len(name))
        inst_lines.append(f"        .{name:<{max_name_len}} ({name})")
        
    code.append(",\n".join(inst_lines))
    code.append("    );")
    code.append("")
    
    # C. Clock Generation
    if clk_port:
        clk_name = clk_port["name"]
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Clock Generation")
        code.append("    // ----------------------------------------------------------------------")
        code.append("    localparam CLK_PERIOD = 10; // 100 MHz clock")
        code.append("    initial begin")
        code.append(f"        {clk_name} = 0;")
        code.append(f"        forever #(CLK_PERIOD/2) {clk_name} = ~{clk_name};")
        code.append("    end")
        code.append("")

    # D. Reset Sequence
    if rst_port:
        rst_name = rst_port["name"]
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Reset Sequence")
        code.append("    // ----------------------------------------------------------------------")
        code.append("    initial begin")
        if is_active_low_reset:
            code.append(f"        {rst_name} = 0; // Assert reset")
            code.append("        #20;            // Wait 20ns")
            code.append(f"        {rst_name} = 1; // De-assert reset")
        else:
            code.append(f"        {rst_name} = 1; // Assert reset")
            code.append("        #20;            // Wait 20ns")
            code.append(f"        {rst_name} = 0; // De-assert reset")
        code.append("    end")
        code.append("")

    # E. Test Stimulus Block
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Test Stimulus")
    code.append("    // ----------------------------------------------------------------------")
    code.append("    initial begin")
    code.append("        // 1. Initialize Inputs")
    for port in ports:
        if port["dir"] == "IN":
            name = port["name"]
            # Skip initializing clk/rst since they have separate blocks
            if clk_port and name == clk_port["name"]:
                continue
            if rst_port and name == rst_port["name"]:
                continue
            code.append(f"        {name} = 0;")
            
    code.append("")
    
    if clk_port:
        clk_name = clk_port["name"]
        if rst_port:
            rst_name = rst_port["name"]
            code.append("        // 2. Wait for Reset release")
            if is_sync_reset:
                # Synchronous reset release
                code.append(f"        @ (posedge {clk_name});")
                # wait until reset is de-asserted
                deassert_val = "1" if is_active_low_reset else "0"
                code.append(f"        wait({rst_name} == {deassert_val});")
                code.append(f"        @ (posedge {clk_name});")
            else:
                # Asynchronous reset release
                deassert_edge = "posedge" if is_active_low_reset else "negedge"
                code.append(f"        @ ({deassert_edge} {rst_name});")
                code.append(f"        @ (posedge {clk_name});")
        else:
            code.append("        // 2. Wait clock cycles")
            code.append(f"        repeat(5) @(posedge {clk_name});")
    else:
        code.append("        // 2. Wait for initial setup")
        code.append("        #10;")
        
    code.append("")
    code.append("        // 3. User Stimulus")
    code.append("        $display(\"[TB] Starting test...\");")
    code.append("        #100;")
    code.append("        ")
    code.append("        // Add your stimulus signals here")
    code.append("        ")
    code.append("        #100;")
    code.append("        $display(\"[TB] Test completed successfully!\");")
    code.append("        $finish;")
    code.append("    end")
    code.append("")
    
    # F. Optional Waveform Dumping
    code.append("    // ----------------------------------------------------------------------")
    code.append("    // Waveform Dumping (vcd/fsdb)")
    code.append("    // ----------------------------------------------------------------------")
    code.append("    initial begin")
    code.append(f"        $dumpfile(\"{tb_name}.vcd\");")
    code.append("        $dumpvars(0, {tb_name});")
    code.append("    end")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)
