import os

def format_width(width):
    w = width.strip()
    if not w or w == "1":
        return ""
    if not w.startswith("["):
        try:
            val = int(w)
            if val > 1:
                return f" [{val-1}:0]"
        except ValueError:
            pass
        return f" [{w}]"
    return f" {w}"

def format_task_width(width):
    w = width.strip()
    if not w or w == "1":
        return ""
    if not w.startswith("["):
        try:
            val = int(w)
            if val > 1:
                return f"[{val-1}:0] "
        except ValueError:
            pass
        return f" [{w}]"
    return f"{w} "

def generate_module_code(module_name, ports, hdl_lang="SystemVerilog"):
    """
    Generates module skeleton code for the chosen HDL.
    """
    if not module_name:
        module_name = "unnamed_module"
        
    if hdl_lang == "Verilog":
        code = []
        code.append("`timescale 1ns / 1ps")
        code.append("// ==========================================================================")
        code.append(f"// Module: {module_name}")
        code.append("// Generated by Tools HDL")
        code.append("// ==========================================================================")
        code.append(f"module {module_name} (")
        
        port_lines = []
        for i, port in enumerate(ports):
            name = port["name"] or f"port_{i}"
            w = port["width"].strip()
            width_str = ""
            if w and w != "1":
                if w.startswith("["):
                    width_str = w + " "
                else:
                    try:
                        val = int(w)
                        if val > 1:
                            width_str = f"[{val-1}:0] "
                        else:
                            width_str = ""
                    except ValueError:
                        width_str = f"[{w}] "
            
            if port["dir"] == "IN":
                direction = "input"
                type_str = ""
            elif port["dir"] == "OUT":
                direction = "output"
                type_str = "reg "
            else:
                direction = "inout"
                type_str = ""
                
            dir_pad = direction.ljust(7)
            w_pad = width_str.ljust(8) if width_str else "        "
            line = f"    {dir_pad} {type_str}{w_pad}{name}"
            port_lines.append(line)
            
        code.append(",\n".join(port_lines))
        code.append(");")
        code.append("")
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Module Implementation")
        code.append("    // ----------------------------------------------------------------------")
        code.append("")
        code.append("endmodule")
        return "\n".join(code)
        
    elif hdl_lang == "VHDL":
        code = []
        code.append("library ieee;")
        code.append("use ieee.std_logic_1164.all;")
        code.append("use ieee.numeric_std.all;")
        code.append("")
        code.append("-- ==========================================================================")
        code.append(f"-- Entity: {module_name}")
        code.append("-- Generated by Tools HDL")
        code.append("-- ==========================================================================")
        code.append(f"entity {module_name} is")
        code.append("    port (")
        
        port_lines = []
        for i, port in enumerate(ports):
            name = port["name"] or f"port_{i}"
            direction = "in" if port["dir"] == "IN" else ("out" if port["dir"] == "OUT" else "inout")
            
            w = port["width"].strip()
            if not w or w == "1":
                type_str = "std_logic"
            else:
                clean_w = w.replace("[", "").replace("]", "").strip()
                if ":" in clean_w:
                    left, right = clean_w.split(":", 1)
                    left = left.strip()
                    right = right.strip()
                    try:
                        l_int = int(left)
                        r_int = int(right)
                        if l_int < r_int:
                          type_str = f"std_logic_vector({l_int} to {r_int})"
                        else:
                          type_str = f"std_logic_vector({l_int} downto {r_int})"
                    except ValueError:
                        type_str = f"std_logic_vector({left} downto {right})"
                else:
                    try:
                        val = int(clean_w)
                        if val > 1:
                            type_str = f"std_logic_vector({val - 1} downto 0)"
                        else:
                            type_str = "std_logic"
                    except ValueError:
                        type_str = f"std_logic_vector({clean_w} downto 0)"
                        
            port_lines.append(f"        {name:<15} : {direction:<5} {type_str}")
            
        code.append(";\n".join(port_lines))
        code.append("    );")
        code.append(f"end entity {module_name};")
        code.append("")
        code.append(f"architecture rtl of {module_name} is")
        code.append("begin")
        code.append("")
        code.append("    -- ----------------------------------------------------------------------")
        code.append("    -- Module Implementation")
        code.append("    -- ----------------------------------------------------------------------")
        code.append("")
        code.append("end architecture rtl;")
        return "\n".join(code)

    else:
        # Default SystemVerilog
        code = []
        code.append("`timescale 1ns / 1ps")
        code.append("// ==========================================================================")
        code.append(f"// Module: {module_name}")
        code.append("// Generated by Tools HDL")
        code.append("// ==========================================================================")
        code.append(f"module {module_name} (")
        
        port_lines = []
        for i, port in enumerate(ports):
            name = port["name"] or f"port_{i}"
            direction = "input " if port["dir"] == "IN" else "output"
            if port["dir"] == "INOUT":
                direction = "inout "
                
            width_str = format_width(port["width"])
            dir_pad = direction.ljust(7)
            type_str = "logic"
            w_pad = width_str.ljust(8) if width_str else "        "
            
            line = f"    {dir_pad} {type_str} {w_pad} {name}"
            port_lines.append(line)
            
        code.append(",\n".join(port_lines))
        code.append(");")
        code.append("")
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Module Implementation")
        code.append("    // ----------------------------------------------------------------------")
        code.append("")
        code.append("endmodule")
        return "\n".join(code)

def generate_testbench_code(module_name, ports, is_sync_reset=False, is_active_low_reset=True, tb_mode="standalone", hdl_lang="SystemVerilog"):
    """
    Generates a testbench for the chosen HDL.
    """
    if not module_name:
        module_name = "unnamed_module"
        
    if hdl_lang == "Verilog":
        tb_name = f"{module_name}_tb"
        
        # Identify clock and reset
        clk_port = None
        rst_port = None
        for p in ports:
            name_lower = p["name"].lower()
            if p["dir"] == "IN":
                if name_lower in ["clk", "clock", "i_clk"]:
                    clk_port = p
                elif name_lower in ["rst", "reset", "rst_n", "i_rst", "rst_b"]:
                    rst_port = p
                    
        # Fallback search
        if not clk_port:
            for p in ports:
                if p["dir"] == "IN" and "clk" in p["name"].lower():
                    clk_port = p
                    break
        if not rst_port:
            for p in ports:
                if p["dir"] == "IN" and "rst" in p["name"].lower():
                    rst_port = p
                    break
                    
        clk_name = clk_port["name"] if clk_port else None
        rst_name = rst_port["name"] if rst_port else None
        
        code = []
        code.append("`define CLR_RESET  \"\\033[0m\"")
        code.append("`define CLR_RED    \"\\033[1;31m\"")
        code.append("`define CLR_GREEN  \"\\033[1;32m\"")
        code.append("`define CLR_YELLOW \"\\033[1;33m\"")
        code.append("`define CLR_BLUE   \"\\033[1;34m\"")
        code.append("")
        
        if clk_port:
            code.append("`define PERIOD 10")
            code.append("")
            
        code.append("`timescale 1ns / 1ps")
        code.append("")
        code.append(f"module {tb_name};")
        code.append("")
        code.append("    integer errors = 0;")
        code.append("    integer tests_run = 0;")
        code.append("")
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Signals")
        code.append("    // ----------------------------------------------------------------------")
        
        max_name_len = max([len(p["name"]) for p in ports]) if ports else 10
        
        for port in ports:
            name = port["name"]
            w = port["width"].strip()
            width_str = ""
            if w and w != "1":
                if w.startswith("["):
                    width_str = w + " "
                else:
                    try:
                        val = int(w)
                        if val > 1:
                            width_str = f"[{val-1}:0] "
                        else:
                            width_str = ""
                    except ValueError:
                        width_str = f"[{w}] "
            
            if port["dir"] == "IN":
                if name == clk_name:
                    code.append(f"    reg {name} = 0;")
                else:
                    code.append(f"    reg {width_str}{name};")
            else:
                code.append(f"    wire {width_str}{name};")
                
        code.append("")
        
        if clk_name:
            code.append("    always")
            code.append("        #(`PERIOD/2) " + clk_name + " = ~" + clk_name + ";")
            code.append("")
            
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // DUT Instantiation")
        code.append("    // ----------------------------------------------------------------------")
        code.append(f"    {module_name} dut (")
        inst_lines = []
        for port in ports:
            name = port["name"]
            inst_lines.append(f"        .{name:<{max_name_len}} ({name})")
        code.append(",\n".join(inst_lines))
        code.append("    );")
        code.append("")
        
        task_inputs = [p for p in ports if p["dir"] == "IN" and p["name"] != clk_name]
        task_outputs = [p for p in ports if p["dir"] == "OUT" or p["dir"] == "INOUT"]
        
        # Verification Task
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Verification Task")
        code.append("    // ----------------------------------------------------------------------")
        code.append(f"    task verification_{module_name};")
        
        for p in task_inputs:
            w = p["width"].strip()
            width_str = ""
            if w and w != "1":
                if w.startswith("["):
                    width_str = w + " "
                else:
                    try:
                        val = int(w)
                        if val > 1:
                            width_str = f"[{val-1}:0] "
                        else:
                            width_str = ""
                    except ValueError:
                        width_str = f"[{w}] "
            code.append(f"        input {width_str}{p['name']}_test;")
            
        for p in task_outputs:
            w = p["width"].strip()
            width_str = ""
            if w and w != "1":
                if w.startswith("["):
                    width_str = w + " "
                else:
                    try:
                        val = int(w)
                        if val > 1:
                            width_str = f"[{val-1}:0] "
                        else:
                            width_str = ""
                    except ValueError:
                        width_str = f"[{w}] "
            code.append(f"        input {width_str}{p['name']}_expect;")
            
        code.append("        begin")
        code.append("            tests_run = tests_run + 1;")
        for p in task_inputs:
            code.append(f"            {p['name']} = {p['name']}_test;")
            
        if clk_name:
            code.append("            #(`PERIOD);")
        else:
            code.append("            #10;")
            
        checks = []
        for p in task_outputs:
            checks.append(f"{p['name']} !== {p['name']}_expect")
        check_cond = " || ".join(checks) if checks else "1'b0"
        
        err_format_args = ["tests_run"]
        err_format_str = f"  [ ERROR ] Test %02d: "
        for p in task_inputs:
            err_format_str += f"{p['name']}:%h "
            err_format_args.append(f"{p['name']}_test")
        err_format_str += "| "
        for p in task_outputs:
            err_format_str += f"Actual {p['name']}:%h (Expected:%h) "
            err_format_args.append(p["name"])
            err_format_args.append(f"{p['name']}_expect")
            
        success_format_args = ["tests_run"]
        success_format_str = f"  [SUCCESS] Test %02d: "
        for p in task_inputs:
            success_format_str += f"{p['name']}:%h "
            success_format_args.append(f"{p['name']}_test")
        success_format_str += "= "
        for p in task_outputs:
            success_format_str += f"{p['name']}:%h "
            success_format_args.append(p["name"])
            
        code.append(f"            if ({check_cond}) begin")
        code.append(f"                $display(\"%s{err_format_str}%s\", `CLR_RED, " + ", ".join(err_format_args) + ", `CLR_RESET);")
        code.append("                errors = errors + 1;")
        code.append("            end else begin")
        code.append(f"                $display(\"%s{success_format_str}%s\", `CLR_GREEN, " + ", ".join(success_format_args) + ", `CLR_RESET);")
        code.append("            end")
        code.append("        end")
        code.append("    endtask")
        code.append("")
        
        # Initial block
        code.append("    initial begin")
        if tb_mode == "chained":
            code.append("        // Wait for master start trigger")
            code.append("        @(master_tb.master_is_done);")
            code.append("")
        if tb_mode == "standalone":
            code.append("        // Waveform dumping")
            code.append("        $dumpfile(\"build/simulation.vcd\");")
            code.append(f"        $dumpvars(0, {tb_name});")
            code.append("")
            
        code.append(f"        $display(\"%s-- {module_name} Test Bench --%s\", `CLR_BLUE, `CLR_RESET);")
        
        if rst_port:
            rst_name = rst_port["name"]
            init_val = "0" if is_active_low_reset else "1"
            deassert_val = "1" if is_active_low_reset else "0"
            code.append(f"        {rst_name} = {init_val};")
            code.append("        #20;")
            code.append(f"        {rst_name} = {deassert_val};")
            code.append("")
            
        code.append("        $display(\"%s[ WARNING ] Test cases not implemented!%s\", `CLR_RED, `CLR_RESET);")
        code.append("")
        code.append("        // ==========================================")
        code.append("        // 1. Initial Test Cases")
        code.append("        // ==========================================")
        code.append("        $display(\"* Running test cases...\");")
        
        mock_args_test = []
        mock_args_expect = []
        for p in task_inputs:
            val = "0"
            if p["name"] == rst_port["name"] if rst_port else False:
                val = "1" if is_active_low_reset else "0"
            elif p["width"] != "1":
                val = "8'h00"
            mock_args_test.append(val)
        for p in task_outputs:
            val = "0"
            if p["width"] != "1":
                val = "8'h00"
            mock_args_expect.append(val)
            
        all_mock_args = mock_args_test + mock_args_expect
        args_str = ", ".join(all_mock_args)
        code.append(f"        verification_{module_name}({args_str});")
        code.append("")
        code.append("        // ==========================================")
        code.append("        // End of Simulation")
        code.append("        // ==========================================")
        code.append(f"        if (errors == 0) $display(\"%s   END : %0d Tests executed | %0d Errors(s)%s\", `CLR_GREEN, tests_run, errors, `CLR_RESET);")
        code.append(f"        else             $display(\"%s   END : %0d Tests executed | %0d Errors(s)%s\", `CLR_RED, tests_run, errors, `CLR_RESET);")
        code.append("")
        if tb_mode == "chained":
            code.append(f"        // Trigger completion event in master")
            code.append(f"        -> master_tb.{module_name}_is_done;")
            code.append("")
        if tb_mode == "standalone":
            code.append("        $finish;")
        code.append("    end")
        code.append("")
        code.append("endmodule")
        return "\n".join(code)
        
    elif hdl_lang == "VHDL":
        tb_name = f"{module_name}_tb"
        
        # Identify clock and reset
        clk_port = None
        rst_port = None
        for p in ports:
            name_lower = p["name"].lower()
            if p["dir"] == "IN":
                if name_lower in ["clk", "clock", "i_clk"]:
                    clk_port = p
                elif name_lower in ["rst", "reset", "rst_n", "i_rst", "rst_b"]:
                    rst_port = p
                    
        # Fallback search
        if not clk_port:
            for p in ports:
                if p["dir"] == "IN" and "clk" in p["name"].lower():
                    clk_port = p
                    break
        if not rst_port:
            for p in ports:
                if p["dir"] == "IN" and "rst" in p["name"].lower():
                    rst_port = p
                    break
                    
        clk_name = clk_port["name"] if clk_port else None
        rst_name = rst_port["name"] if rst_port else None
        
        code = []
        code.append("library ieee;")
        code.append("use ieee.std_logic_1164.all;")
        code.append("use ieee.numeric_std.all;")
        code.append("use std.textio.all;")
        code.append("")
        code.append(f"entity {tb_name} is")
        code.append(f"end entity {tb_name};")
        code.append("")
        code.append(f"architecture sim of {tb_name} is")
        
        # Component Declaration
        code.append(f"    -- Component declaration for the Device Under Test (DUT)")
        code.append(f"    component {module_name} is")
        code.append("        port (")
        
        comp_ports = []
        for p in ports:
            name = p["name"]
            direction = "in" if p["dir"] == "IN" else ("out" if p["dir"] == "OUT" else "inout")
            w = p["width"].strip()
            if not w or w == "1":
                type_str = "std_logic"
            else:
                clean_w = w.replace("[", "").replace("]", "").strip()
                if ":" in clean_w:
                    left, right = clean_w.split(":", 1)
                    left = left.strip()
                    right = right.strip()
                    try:
                        l_int = int(left)
                        r_int = int(right)
                        if l_int < r_int:
                            type_str = f"std_logic_vector({l_int} to {r_int})"
                        else:
                            type_str = f"std_logic_vector({l_int} downto {r_int})"
                    except ValueError:
                        type_str = f"std_logic_vector({left} downto {right})"
                else:
                    try:
                        val = int(clean_w)
                        if val > 1:
                            type_str = f"std_logic_vector({val - 1} downto 0)"
                        else:
                            type_str = "std_logic"
                    except ValueError:
                        type_str = f"std_logic_vector({clean_w} downto 0)"
            comp_ports.append(f"            {name:<15} : {direction:<5} {type_str}")
        code.append(";\n".join(comp_ports))
        code.append("        );")
        code.append("    end component;")
        code.append("")
        
        # Signals
        code.append("    -- Signals for driving the DUT inputs and observing outputs")
        for p in ports:
            name = p["name"]
            w = p["width"].strip()
            if not w or w == "1":
                type_str = "std_logic"
                init_val = " := '0'" if p["dir"] == "IN" else ""
            else:
                clean_w = w.replace("[", "").replace("]", "").strip()
                if ":" in clean_w:
                    left, right = clean_w.split(":", 1)
                    left = left.strip()
                    right = right.strip()
                    try:
                        l_int = int(left)
                        r_int = int(right)
                        if l_int < r_int:
                            type_str = f"std_logic_vector({l_int} to {r_int})"
                        else:
                            type_str = f"std_logic_vector({l_int} downto {r_int})"
                    except ValueError:
                        type_str = f"std_logic_vector({left} downto {right})"
                else:
                    try:
                        val = int(clean_w)
                        if val > 1:
                            type_str = f"std_logic_vector({val - 1} downto 0)"
                        else:
                            type_str = "std_logic"
                    except ValueError:
                        type_str = f"std_logic_vector({clean_w} downto 0)"
                init_val = " := (others => '0')" if p["dir"] == "IN" else ""
            code.append(f"    signal {name:<15} : {type_str}{init_val};")
            
        code.append("")
        if clk_name:
            code.append("    constant PERIOD : time := 10 ns;")
            code.append("")
            
        code.append("begin")
        code.append("")
        code.append("    -- Instantiate the Device Under Test (DUT)")
        code.append("    dut : component " + module_name)
        code.append("        port map (")
        inst_maps = []
        for p in ports:
            name = p["name"]
            inst_maps.append(f"            {name:<15} => {name}")
        code.append(",\n".join(inst_maps))
        code.append("        );")
        code.append("")
        
        if clk_name:
            code.append("    -- Clock generation process")
            code.append("    clk_process : process")
            code.append("    begin")
            code.append("        while now < 10000 ns loop  -- safety guard to end simulation")
            code.append(f"            {clk_name} <= '0';")
            code.append("            wait for PERIOD / 2;")
            code.append(f"            {clk_name} <= '1';")
            code.append("            wait for PERIOD / 2;")
            code.append("        end loop;")
            code.append("        wait;")
            code.append("    end process;")
            code.append("")
            
        code.append("    -- Stimulus process")
        code.append("    stim_proc : process")
        code.append("        variable l : line;")
        code.append("        variable tests_run : integer := 0;")
        code.append("        variable errors    : integer := 0;")
        code.append("    begin")
        code.append(f"        write(l, string'(\"-- {module_name} Test Bench --\"));")
        code.append("        writeline(output, l);")
        code.append("")
        
        if rst_name:
            init_val = "'0'" if is_active_low_reset else "'1'"
            deassert_val = "'1'" if is_active_low_reset else "'0'"
            code.append(f"        -- Reset sequence")
            code.append(f"        {rst_name} <= {init_val};")
            code.append("        wait for 20 ns;")
            code.append(f"        {rst_name} <= {deassert_val};")
            code.append("        wait for 20 ns;")
            code.append("")
            
        code.append("        write(l, string'(\"[ WARNING ] Test cases not implemented!\"));")
        code.append("        writeline(output, l);")
        code.append("")
        
        code.append("        -- ==========================================")
        code.append("        -- 1. Initial Test Cases")
        code.append("        -- ==========================================")
        code.append("        tests_run := tests_run + 1;")
        
        task_inputs = [p for p in ports if p["dir"] == "IN" and p["name"] != clk_name and p["name"] != rst_name]
        for p in task_inputs:
            w = p["width"].strip()
            if not w or w == "1":
                code.append(f"        {p['name']} <= '0';")
            else:
                code.append(f"        {p['name']} <= (others => '0');")
                
        if clk_name:
            code.append("        wait for PERIOD;")
        else:
            code.append("        wait for 10 ns;")
            
        code.append("        write(l, string'(\"  [SUCCESS] Test case executed\"));")
        code.append("        writeline(output, l);")
        code.append("")
        
        code.append("        -- ==========================================")
        code.append("        -- End of Simulation")
        code.append("        -- ==========================================")
        code.append("        write(l, string'(\"   END : \") & integer'image(tests_run) & string'(\" Tests run | \") & integer'image(errors) & string'(\" Errors\"));")
        code.append("        writeline(output, l);")
        code.append("        wait;")
        code.append("    end process;")
        code.append("")
        code.append("end architecture sim;")
        return "\n".join(code)
        
    else:
        # Default SystemVerilog
        tb_name = f"{module_name}_tb"
        
        # Identify clock and reset
        clk_port = None
        rst_port = None
        
        for p in ports:
            name_lower = p["name"].lower()
            if p["dir"] == "IN":
                if name_lower in ["clk", "clock", "i_clk"]:
                    clk_port = p
                elif name_lower in ["rst", "reset", "rst_n", "i_rst", "rst_b"]:
                    rst_port = p
                    
        # Fallback search
        if not clk_port:
            for p in ports:
                if p["dir"] == "IN" and "clk" in p["name"].lower():
                    clk_port = p
                    break
        if not rst_port:
            for p in ports:
                if p["dir"] == "IN" and "rst" in p["name"].lower():
                    rst_port = p
                    break
    
        code = []
        
        # 1. Color Macros
        code.append("`define CLR_RESET  \"\\033[0m\"")
        code.append("`define CLR_RED    \"\\033[1;31m\"")
        code.append("`define CLR_GREEN  \"\\033[1;32m\"")
        code.append("`define CLR_YELLOW \"\\033[1;33m\"")
        code.append("`define CLR_BLUE   \"\\033[1;34m\"")
        code.append("")
        
        if clk_port:
            code.append("`define PERIOD 10")
            code.append("")
            
        code.append("`timescale 1ns / 1ps")
        code.append(f"string formatted_msg_{module_name};")
        code.append("")
        code.append(f"module {tb_name};")
        code.append("")
        
        # 2. Stats
        code.append("    int errors = 0;")
        code.append("    int tests_run = 0;")
        code.append("")
        
        # 3. Signals
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Signals")
        code.append("    // ----------------------------------------------------------------------")
        
        max_name_len = max([len(p["name"]) for p in ports]) if ports else 10
        clk_name = clk_port["name"] if clk_port else None
        
        for port in ports:
            name = port["name"]
            width_str = format_width(port["width"])
            w_pad = width_str + " " if width_str else ""
            
            if name == clk_name:
                code.append(f"    logic {name} = 0;")
            else:
                code.append(f"    logic {w_pad}{name};")
                
        code.append("")
        
        # 4. Clock Generation
        if clk_name:
            code.append("    always")
            code.append("        #(`PERIOD/2) " + clk_name + " = ~" + clk_name + ";")
            code.append("")
    
        # 5. DUT
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // DUT Instantiation")
        code.append("    // ----------------------------------------------------------------------")
        code.append(f"    {module_name} dut (")
        
        inst_lines = []
        for port in ports:
            name = port["name"]
            inst_lines.append(f"        .{name:<{max_name_len}} ({name})")
        code.append(",\n".join(inst_lines))
        code.append("    );")
        code.append("")
        
        # 6. Verification Task
        task_inputs = [p for p in ports if p["dir"] == "IN" and p["name"] != clk_name]
        task_outputs = [p for p in ports if p["dir"] == "OUT" or p["dir"] == "INOUT"]
        
        code.append("    // ----------------------------------------------------------------------")
        code.append("    // Verification Task")
        code.append("    // ----------------------------------------------------------------------")
        code.append(f"    task verification_{module_name}(")
        
        task_args = []
        for p in task_inputs:
            w = format_task_width(p["width"])
            task_args.append(f"        input  logic {w}{p['name']}_test")
            
        for p in task_outputs:
            w = format_task_width(p["width"])
            task_args.append(f"        input  logic {w}{p['name']}_expect")
            
        code.append(",\n".join(task_args))
        code.append("    );")
        code.append("        begin")
        code.append("            tests_run++;")
        code.append("")
        code.append("            // Apply inputs")
        for p in task_inputs:
            code.append(f"            {p['name']} = {p['name']}_test;")
        
        if clk_name:
            code.append("            #(`PERIOD);")
        else:
            code.append("            #10;")
            
        code.append("")
        
        checks = []
        for p in task_outputs:
            checks.append(f"{p['name']} !== {p['name']}_expect")
        check_cond = " || ".join(checks) if checks else "1'b0"
        
        err_format_args = ["tests_run"]
        err_format_str = f"  [ ERROR ] Test %02d: "
        in_prints = []
        for p in task_inputs:
            in_prints.append(f"{p['name']}:%h")
            err_format_args.append(f"{p['name']}_test")
        err_format_str += " ".join(in_prints)
        
        out_prints = []
        for p in task_outputs:
            out_prints.append(f"Actual {p['name']}:%h (Expected:%h)")
            err_format_args.append(p["name"])
            err_format_args.append(f"{p['name']}_expect")
        err_format_str += " | " + ", ".join(out_prints)
        
        success_format_args = ["tests_run"]
        success_format_str = f"  [SUCCESS] Test %02d: "
        success_in_prints = []
        for p in task_inputs:
            success_in_prints.append(f"{p['name']}:%h")
            success_format_args.append(f"{p['name']}_test")
        success_format_str += " ".join(success_in_prints)
        
        success_out_prints = []
        for p in task_outputs:
            success_out_prints.append(f"{p['name']}:%h")
            success_format_args.append(p["name"])
        success_format_str += " = " + ", ".join(success_out_prints)
    
        code.append(f"            if ({check_cond}) begin")
        code.append(f"                formatted_msg_{module_name} = $sformatf(\"{err_format_str}\",")
        code.append("                    " + ", ".join(err_format_args) + ");")
        code.append(f"                $display(\"%s%s%s\", `CLR_RED, formatted_msg_{module_name}, `CLR_RESET);")
        code.append("                errors++;")
        code.append("            end else begin")
        code.append(f"                formatted_msg_{module_name} = $sformatf(\"{success_format_str}\",")
        code.append("                    " + ", ".join(success_format_args) + ");")
        code.append(f"                $display(\"%s%s%s\", `CLR_GREEN, formatted_msg_{module_name}, `CLR_RESET);")
        code.append("            end")
        code.append("        end")
        code.append("    endtask")
        code.append("")
        
        # 7. Initial block
        code.append("    initial begin")
        
        if tb_mode == "chained":
            code.append("        // Wait for master start trigger")
            code.append("        @(master_tb.master_is_done);")
            code.append("")
            
        if tb_mode == "standalone":
            code.append("        // Waveform dumping")
            code.append("        $dumpfile(\"build/simulation.vcd\");")
            code.append(f"        $dumpvars(0, {tb_name});")
            code.append("")
            
        code.append(f"        formatted_msg_{module_name} = $sformatf(\"-- {module_name} Test Bench --\");")
        code.append(f"        $display(\"%s%s%s\", `CLR_BLUE, formatted_msg_{module_name}, `CLR_RESET);")
        
        if rst_port:
            rst_name = rst_port["name"]
            init_val = "0" if is_active_low_reset else "1"
            deassert_val = "1" if is_active_low_reset else "0"
            code.append(f"        {rst_name} = {init_val};")
            code.append("        #20;")
            code.append(f"        {rst_name} = {deassert_val};")
            code.append("")
            
        code.append("        // Warning by default")
        code.append("        $display(\"%s[ WARNING ] Test cases not implemented!%s\", `CLR_RED, `CLR_RESET);")
        code.append("")
        
        code.append("        // ==========================================")
        code.append("        // 1. Initial Test Cases")
        code.append("        // ==========================================")
        code.append("        $display(\"* Running test cases...\");")
        
        mock_args_test = []
        mock_args_expect = []
        
        for p in task_inputs:
            val = "0"
            if p["name"] == rst_port["name"] if rst_port else False:
                val = "1" if is_active_low_reset else "0"
            elif p["width"] != "1":
                val = "8'h00"
            mock_args_test.append(val)
            
        for p in task_outputs:
            val = "0"
            if p["width"] != "1":
                val = "8'h00"
            mock_args_expect.append(val)
            
        all_mock_args = mock_args_test + mock_args_expect
        args_str = ", ".join(all_mock_args)
        
        code.append(f"        verification_{module_name}({args_str});")
        code.append("")
        
        # End of Simulation
        code.append("        // ==========================================")
        code.append("        // End of Simulation")
        code.append("        // ==========================================")
        code.append(f"        formatted_msg_{module_name} = $sformatf(\"   END : %0d Tests executed | %0d Errors(s)\", tests_run, errors);")
        code.append(f"        if (errors == 0) $display(\"%s%s%s\", `CLR_GREEN, formatted_msg_{module_name}, `CLR_RESET);")
        code.append(f"        else             $display(\"%s%s%s\", `CLR_RED, formatted_msg_{module_name}, `CLR_RESET);")
        code.append("")
        
        if tb_mode == "chained":
            code.append(f"        // Trigger completion event in master")
            code.append(f"        -> master_tb.{module_name}_is_done;")
            code.append("")
            
        if tb_mode == "standalone":
            code.append("        $finish;")
            
        code.append("    end")
        code.append("")
        code.append("endmodule")
        return "\n".join(code)

def generate_master_tb_code(sub_tbs):
    """
    Generates a top-level master_tb module.
    """
    code = []
    code.append("`timescale 1ns / 1ps")
    code.append("")
    code.append("module master_tb;")
    code.append("")
    code.append("    // Synchronization Events")
    code.append("    event master_is_done;")
    
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"    event {name}_is_done;")
    code.append("")
    
    code.append("    // Sub-Testbench Instantiations")
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"    {name}_tb u_{name}_tb();")
    code.append("")
    
    code.append("    initial begin")
    code.append("        $dumpfile(\"build/simulation.vcd\");")
    code.append("        $dumpvars(0, master_tb);")
    code.append("        ")
    code.append("        // Start all testbenches")
    code.append("        -> master_is_done;")
    code.append("        ")
    code.append("        // Wait for each testbench to complete sequentially")
    for tb in sub_tbs:
        name = tb["module_name"]
        code.append(f"        @({name}_is_done);")
    code.append("        ")
    code.append("        $finish;")
    code.append("    end")
    code.append("")
    code.append("endmodule")
    
    return "\n".join(code)
