# Translations system
current_language = "en"

TRANSLATIONS = {
    "en": {
        "title": "Tools HDL V0.1.1",
        "module_name": "Module Name:",
        "active_low": "Active Low Reset",
        "sync_reset": "Synchronous Reset",
        "add_clk": "Add Clock",
        "add_rst": "Add Reset",
        "tb_settings": "Testbench Settings",
        "module_ports": "Module Ports",
        "Standalone": "Standalone",
        "With Master": "With Master",
        "Block Diagram": "Block Diagram",
        "Code Preview": "Code Preview",
        "Paste or Import": "Paste or Import",
        "Module Code": "Module Code",
        "Testbench Code": "Testbench Code",
        "Master TB Code": "Master TB Code",
        "Import SV File": "Import SV File",
        "Parse Pasted Code": "Parse Pasted Code",
        "Copy Code": "Copy Code",
        "Preferences": "Preferences",
        "pref_title": "Preferences",
        "pref_ui_scale": "UI Size:",
        "pref_lang": "Language:",
        "pref_editor_size": "Editor Font Size:",
        "pref_theme": "Theme:",
        "pref_hdl": "HDL Language:",
        "Close": "Close",
        "Active Low Reset": "Active Low Reset",
        "Synchronous Reset": "Synchronous Reset",
        "Add Clock": "Add Clock",
        "Add Reset": "Add Reset",
        "+ Input": "+ Input",
        "+ Output": "+ Output",
        "close": "Close",
    },
    "fr": {
        "title": "Tools HDL V0.1.1",
        "module_name": "Nom du Module :",
        "active_low": "Reset Actif Bas",
        "sync_reset": "Reset Synchrone",
        "add_clk": "Ajouter Horloge",
        "add_rst": "Ajouter Reset",
        "tb_settings": "Paramètres Testbench",
        "module_ports": "Ports du Module",
        "Standalone": "Autonome",
        "With Master": "Avec Master",
        "Block Diagram": "Schéma Bloc",
        "Code Preview": "Aperçu du Code",
        "Paste or Import": "Coller ou Importer",
        "Module Code": "Code Module",
        "Testbench Code": "Code Testbench",
        "Master TB Code": "Code Master TB",
        "Import SV File": "Importer Fichier SV",
        "Parse Pasted Code": "Analyser Code Collé",
        "Copy Code": "Copier Code",
        "Preferences": "Préférences",
        "pref_title": "Préférences",
        "pref_ui_scale": "Taille UI :",
        "pref_lang": "Langue :",
        "pref_editor_size": "Taille Code :",
        "pref_theme": "Thème :",
        "pref_hdl": "Langage HDL :",
        "Close": "Fermer",
        "Active Low Reset": "Reset Actif Bas",
        "Synchronous Reset": "Reset Synchrone",
        "Add Clock": "Ajouter Horloge",
        "Add Reset": "Ajouter Reset",
        "+ Input": "+ Entrée",
        "+ Output": "+ Sortie",
        "close": "Fermer",
    }
}

def tr(key):
    if key in TRANSLATIONS[current_language]:
        return TRANSLATIONS[current_language][key]
    return key
